import { Transaction } from "@types";

export const transactionData: Transaction[] = [
  {
    id: 1,
    description: "Card declined at Netflix",
    amount: "$8.79",
    date: "Today",
    status: "failed",
  },
  {
    id: 2,
    description: "Received from bank Daniel Agoziem",
    amount: "₦35,000",
    date: "Today",
    status: "success",
    type: "received",
    bank: "GTBank",
  },
  {
    id: 3,
    description: "Sent to bank @chinonsogreat",
    amount: "₦40,000",
    date: "Today",
    status: "success",
    type: "sent",
    bank: "ZenithBank",
  },
  {
    id: 4,
    description: "Sent to bank Oluwatobi Oseni",
    amount: "₦8,000",
    date: "Today",
    status: "success",
    type: "sent",
    bank: "AccessBank",
  },
  {
    id: 5,
    description: "Reversal for Ref_Temidayo Anifowo..",
    amount: "₦31,950",
    date: "Today",
    status: "success",
    type: "received",
  },
  {
    id: 6,
    description: "Balance Top up for Ghanian Cedi",
    amount: "₵80,000",
    date: "Today",
    status: "success",
    type: "received",
  },
  {
    id: 7,
    description: "Received from @moneymade$$",
    amount: "₦6,900",
    date: "July 2023",
    status: "success",
    type: "received",
  },
  {
    id: 8,
    description: "Spent on NETFLIX.COM",
    amount: "$50.09",
    date: "July 2023",
    status: "success",
    type: "spent",
  },
];
