import { Transaction } from "@types";

export const transactionData: Transaction[] = [
  {
    id: 1,
    description: "Card declined at",
    amount: "$8.79",
    date: "Today",
    status: "failed",
    source: "Netflix",
  },
  {
    id: 2,
    description: "Received from bank",
    amount: "₦35,000",
    date: "Today",
    // status: "success",
    // type: "received",
    bank: "GTBank",
    source: "Daniel Agoziem",
  },
  {
    id: 3,
    description: "Sent to bank",
    amount: "₦40,000",
    date: "Today",
    // status: "success",
    // type: "sent",
    bank: "GTBank",
    source: "@chinonsogreat",
  },
  {
    id: 5,
    description: "Reversal for",
    amount: "₦31,950",
    date: "Today",
    status: "success",
    type: "received",
    source: "Ref_Temidayo Anifowo..",
  },
  {
    id: 6,
    description: "Balance Top up for",
    amount: "₵80,000",
    date: "Today",
    status: "success",
    type: "received",
    source: "Ghanian Cedi",
  },
  {
    id: 4,
    description: "Sent to bank",
    amount: "₦8,000",
    date: "Today",
    // status: "success",
    // type: "sent",
    bank: "GTBank",
    source: "Oluwatobi Oseni",
  },
  {
    id: 7,
    description: "Received from",
    amount: "₦6,900",
    date: "July 2023",
    status: "success",
    type: "received",
    source: "@moneymade$$",
  },
  {
    id: 8,
    description: "Spent on",
    amount: "$50.09",
    date: "July 2023",
    status: "debit",
    type: "spent",
    source: "NETFLIX.COM",
  },
];
